# Server Port for Eureka Naming Server
server.port=8761

# Application Name
spring.application.name=eurekaserver

# Eureka Server Settings
# Since this IS the Eureka server itself, tell it NOT to register with itself!
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO