import React from 'react';
import { CheckCircle2, Printer, Download, ShieldCheck, FileText, ArrowRight } from 'lucide-react';

export const DigitalReceiptModal = ({ receiptData, onFinish }) => {
  if (!receiptData) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content receipt-modal glass-panel">
        <div className="receipt-header">
          <div className="success-badge-large">
            <CheckCircle2 size={48} className="badge-icon" />
          </div>
          <h2>Payment Authorized & Confirmed!</h2>
          <p>Official Digital Receipt generated by Payment Gateway (Port 8083)</p>
        </div>

        <div className="receipt-paper">
          <div className="receipt-paper-header">
            <div>
              <h4 className="company-name">Return Order Management Platform</h4>
              <span className="receipt-subtitle">Logistics & RMA Fulfillment Center</span>
            </div>
            <div className="receipt-number-badge">
              <FileText size={16} /> {receiptData.receiptNumber}
            </div>
          </div>

          <div className="receipt-divider"></div>

          <div className="receipt-details-grid">
            <div className="detail-item">
              <span className="detail-label">Transaction ID:</span>
              <code className="detail-code">{receiptData.transactionId}</code>
            </div>

            <div className="detail-item">
              <span className="detail-label">Payment Status:</span>
              <span className="status-badge-success">{receiptData.paymentStatus}</span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Payment Method:</span>
              <span className="detail-value">{receiptData.paymentProvider} ({receiptData.cardNumberMasked})</span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Transaction Date & Time:</span>
              <span className="detail-value">{new Date(receiptData.timestamp).toLocaleString()}</span>
            </div>

            <div className="detail-item">
              <span className="detail-label">Amount Paid:</span>
              <span className="receipt-amount">₹{receiptData.amountPaid.toFixed(2)} {receiptData.currency}</span>
            </div>
          </div>

          <div className="receipt-footer-note">
            <ShieldCheck size={16} />
            <span>Thank you for trusting us with your component return. A copy has been saved to your account history.</span>
          </div>
        </div>

        <div className="receipt-actions no-print">
          <button type="button" className="btn btn-secondary" onClick={handlePrint}>
            <Printer size={16} /> Print Receipt
          </button>
          <button type="button" className="btn btn-primary btn-lg" onClick={onFinish}>
            Return to Dashboard <ArrowRight size={18} />
          </button>
        </div>
      </div>
    </div>
  );
};
