# Server Port for Config Server
server.port=8888
spring.application.name=configserver

# Use Native File System for Configuration Repository
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Eureka Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=true
eureka.instance.prefer-ip-address=true